### ISSUE TITLE
sdk cannot resolve data file from Full Stack project

### ISSUE THREAD

**Issue by jia-tse-zocdoc** [optimizely/android-sdk#141]
I'm using this android-sdk in conjunction with a Full Stack project setup on Optimizely. The SDK is trying to fetch the data file at https://cdn.optimizely.com/public/<project_id>/datafile_v3.json, and is getting a 503. 

Upon further investigation, if we update DatafileService.DATAFILE_VERSION to "2" instead of "3", then this seems to work fine. Can we make DATAFILE_VERSION a configurable value?

According to the documentation we received from the Optimizely team about cross-platform experiments (https://docs.google.com/document/d/1BHcd4iv_ZHNFfmutS_qMNUpB6UBDIerKnK1ezqh-DN0/edit),

the only difference is the version number.

**Comment by thomaszurkan-optimizely** [comment]
Hi,
It was decided that rather than make the data file version configurable (out of the box), we would fix it on the backend by providing both a v2 and v3 datafile for full stack projects.  There is an open ticket on that now and I hope to have it resolved as soon as possible.  In the time being, using your own datafile handler that uses V2 would work.  Thanks for the feedback!  It is greatly appreciated!

**Comment by jia-tse-zocdoc** [comment]
Thanks, let's leave this issue open until v2 support is ready?

**Comment by jia-tse-zocdoc** [comment]
Also -- I didn't use my own data file handler. I'm using the provided Default implementation. All I did was change `DatafileService.DATAFILE_VERSION` from "3" to "2" and seems to work fine.

**Comment by thomaszurkan-optimizely** [comment]
@jia-tse-zocdoc .  I know you haven't seen a lot of movement here. But, with the release of 2.0.0, if you have feature management enabled, you can use v4 datafile for any full stack or mobile project. So, I'm going to close this now.  Thanks!
