### ISSUE TITLE
Proguard rules are too broad

### ISSUE THREAD

**Issue by tasomaniac** [optimizely/android-sdk#148]
I was just upgrading SDK we use to version 1.4.0 and saw that you have this entry`Fix proguard rules.`

I was curious what you did and looked at the `consumerProguardFiles` and saw the entry `-keep class com.optimizely.ab.** { *; }`

This is unacceptable for us. And it is really irresponsible. Just for this reason, we are not upgrading the SDK for now. 

Until now, we have only the following in our proguard file and works fine for us. `-keep interface com.fasterxml.jackson.annotation.** {*;}`

As a library developer, you should be very careful about this. You should only keep methods (and maybe classes) where you use reflection. Other than that, proguard is intelligent enough to do the right thing. 

Unfortunately Android build tools does not allow use to ignore what libraries put in `consumerProguardFiles`. This means that our method count will just increase for no reason when we upgrade the library to version 1.4.0

**Comment by thomaszurkan-optimizely** [comment]
Thanks for the feedback.  We are releasing a 1.4.1 very soon.  We will revisit the proguard rules for that release and back off where appropriate.  FYI: the consumerProguardFiles are the recommended proguard settings for Optimizely SDK:
https://developers.optimizely.com/x/solutions/sdks/reference/index.html?language=android&platform=mobile
Rules:
https://developers.optimizely.com/assets/files/proguard-rules.pro

It would seem like intents and other services might not be included since they are not explicitly used (such as the rescheduler).

Can I ask what the difference in method count is?

**Comment by tasomaniac** [comment]
I think it is totally fine to include gson. We also use gson in our project and we have those rules added as well.

But the first rule is not necessary. You don't have to keep **ALL** of your SDK.

In fact we have been very actively using version 1.3.1 and we didn't have any problem so far.

I will check the method count but that it irrelevant to the problem. Imagine all library developers doing this, there would be no point of using proguard.

**Comment by thomaszurkan-optimizely** [comment]
I will definitely remove the broad proguard rule for something more precise.  Fixing it this week and hopefully releasing as well.  Thanks!

**Comment by tasomaniac** [comment]
Thanks for fast feedback. I will report back on method count difference. Looking forward to see and test the change.

**Comment by thomaszurkan-optimizely** [comment]
@tasomaniac please checkout 1.5.0-RC.  I think you will find the narrowed scope of the proguard rules to your liking.  Thanks.  I will be closing this ticket soon.

**Comment by tasomaniac** [comment]
Thanks for taking care of it. Looks good. :+1:

**Comment by thomaszurkan-optimizely** [comment]
narrowed scope on 1.5.0
